### ISSUE TITLE
Update songs.js (use DropBox service )

### ISSUE THREAD

**Issue by subhranshuchoudhury** [subhranshuchoudhury/songplayer#3]
You have to do the things.

1. Add more songs Category wise
2. Add lyrics of every song with a new key called "lyrics"!
3. Add thumbnails.
4. Add any other feature/fields/key-values if you want.

my contact details are on the GitHub profile page.
File Link: https://github.com/subhranshuchoudhury/songplayer/blob/main/src/SongDatabase/songs.js (This file only should update).

**Comment by iks1** [comment]
taking it up please assign

**Comment by subhranshuchoudhury** [comment]
I want this as a backend api using Mongodb & express or anything.

**Comment by subhranshuchoudhury** [comment]
Give it a try and make a good json file for numbers of songs.

**Comment by iks1** [comment]
okay on it
