### ISSUE TITLE
Update the README.md file and create separate Contribution.md file

### ISSUE THREAD

**Issue by subhranshuchoudhury** [subhranshuchoudhury/songplayer#4]
Your work is to update the README.md file and give it a perfect look with a logo and all the features written on it. Also create a contribution.md and shift the present README.md (Only the contribution part) code to that contribution.md file.

contact details are on my GitHub profile.

**Comment by mintxdp** [comment]
Ok, I'll do it.

**Comment by subhranshuchoudhury** [comment]
> Ok, I'll do it.

I will assign this work to you after the event period start for taking contribution.

Assign Date: on **4 April**

**Comment by chaitralikakde** [comment]
I want to contribute on this issue

**Comment by subhranshuchoudhury** [comment]
I will assign this work to you.
